#!/bin/bash
#athor: Kaio Guilherme
x="loop"

menu ()
{
while true $x != "loop"
do
clear
echo "\033[0;34m================================================\033[0m"
echo "\033[0;34m|\033[0m            \033[1;36mSSL Installer: Debian\033[0m             \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m             \033[1;36mchoose your version\033[0m              \033[0;34m|\033[0m"
echo "\033[0;34m================================================\033[0m"
echo "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[0;31m 0) Exit\033[0m                                     \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 1) apache\033[0m                                   \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 2) Nginx \033[0m                                   \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 3) View Certificates     \033[0m                   \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 4) Request new certificate    \033[0m              \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 5) Revoke certificate    \033[0m                   \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 6) change domain         \033[0m                   \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 7) Delete certificate    \033[0m                   \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 8) Try automatic renewal \033[0m                   \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m \033[1;33m 9) Remove Certbot \033[0m                          \033[0;34m|\033[0m"
echo "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
echo "\033[0;34m================================================\033[0m"
echo "\033[0;34m|\033[0m    \033[1;36mCertificate generated by Let's Encrypt\033[0m    \033[0;34m|\033[0m"
echo "\033[0;34m================================================\033[0m"
echo ""
echo "\033[0;36mEnter the desired option: \033[0m"
read x
echo "informed option ($x)"
echo "\033[1;36m================================================\033[0m"

case "$x" in

        0)
        echo " \033[0;31m Going out  \033[0m"
        clear;
        exit;
        

echo "\033[0;34m================================================\033[0m"
;;
        1) #ssl apache install

        apt-get update
        apt-get install software-properties-common -y
        apt-get update
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                 echo " \033[0;32mSuccessfully Updated\033[0m"
        fi
        apt-get install certbot -y
        apt install certbot python3-certbot-apache -y
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo " \033[0;32mCertbot apache Successfully Installed\033[0m"
        fi
        clear
        certbot --apache
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
        2) # ssl nginx install

        apt-get update
        apt-get install software-properties-common -y
        apt-get update
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo " \033[0;32mSuccessfully Updated\033[0m"
        fi
        apt-get install certbot -y
        apt install certbot python3-certbot-nginx -y
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo " \033[0;32mCertbot nginx Successfully Installed\033[0m"
        fi
        clear
        certbot --nginx
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
        3) # view certificates

        certbot certificates
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
        4) #Request new certificate
        certbot certonly
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo " \033[0;32mNew certificate generated successfully\033[0m"
        fi
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
        5) #revoke certificate
        echo "\033[0;34m================================================\033[0m"
        echo "\033[0;34m|\033[0m            \033[1;36mSSL Installer: Debian\033[0m             \033[0;34m|\033[0m"
        echo "\033[0;34m|\033[0m             \033[1;36mRevoke certificate\033[0m               \033[0;34m|\033[0m"
        echo "\033[0;34m================================================\033[0m"
        echo "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
        echo "\033[0;34m|\033[0m \033[1;33m Enter the domain you want to revoke\033[0m         \033[0;34m|\033[0m"
        echo "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
        echo "\033[0;34m================================================\033[0m"
        echo "\033[0;34m|\033[0m    \033[1;36mCertificate generated by Let's Encrypt\033[0m    \033[0;34m|\033[0m"
        echo "\033[0;34m================================================\033[0m"
        echo ""
        echo "\033[0;36mEnter the domain: \033[0m"
        read domain
        certbot revoke --cert-name $domain
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo " \033[0;32mCertbot Successfully Revoked\033[0m"
        fi
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
        6) #change domain
        echo "\033[0;34m================================================\033[0m"
        echo "\033[0;34m|\033[0m            \033[1;36mSSL Installer: Debian\033[0m             \033[0;34m|\033[0m"
        echo "\033[0;34m|\033[0m             \033[1;36mChange domain\033[0m                    \033[0;34m|\033[0m"
        echo "\033[0;34m================================================\033[0m"
        echo "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
        echo "\033[0;34m|\033[0m \033[1;33m Enter the domain you want to change\033[0m         \033[0;34m|\033[0m"
        echo "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
        echo "\033[0;34m================================================\033[0m"
        echo "\033[0;34m|\033[0m    \033[1;36mCertificate generated by Let's Encrypt\033[0m    \033[0;34m|\033[0m"
        echo "\033[0;34m================================================\033[0m"
        echo ""
        echo "\033[0;36mEnter the current domain: \033[0m"
        read domain1
        echo "\033[0;36mEnter the new domain: \033[0m"
        read domain2
        certbot certonly --cert-name example.com -d example.com
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo " \033[0;32m $domain1 domain successfully changed to $domain2\033[0m"
        fi
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
        7) #delete certificate

        certbot delete
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
        8) #automatic renewal

        certbot renew --dry-run
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
        9) #remove certbot

        echo "removing"
        apt remove certbot python3-certbot-apache -y
        apt-get remove certbot -y
        clear
        echo -e " \033[0;32mCertbot Successfully Removed\033[0m"
        echo "press enter to continue"
        read z
echo "\033[0;34m================================================\033[0m"
;;
*)
        echo "Invalid option!"
esac
done
}
menu 
