#!/bin/bash
#athor: Kaio Guilherme
x="loop"

menu ()
{
while true $x != "loop"
do
clear
echo -e "\033[0;34m================================================\033[0m"
echo -e "\033[0;34m|\033[0m            \033[1;36mSSL Installer: Debian\033[0m             \033[0;34m|\033[0m"
echo -e "\033[0;34m|\033[0m             \033[1;36mchoose your version\033[0m              \033[0;34m|\033[0m"
echo -e "\033[0;34m================================================\033[0m"
echo -e "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
echo -e "\033[0;34m|\033[0m \033[0;31m 0) Exit\033[0m                                     \033[0;34m|\033[0m"
echo -e "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
echo -e "\033[0;34m|\033[0m \033[1;33m 1) apache\033[0m                                   \033[0;34m|\033[0m"
echo -e "\033[0;34m|\033[0m \033[1;33m 2) Nginx \033[0m                                   \033[0;34m|\033[0m"
echo -e "\033[0;34m|\033[0m \033[1;33m 3) Try automatic renewal \033[0m                   \033[0;34m|\033[0m"
echo -e "\033[0;34m|\033[0m \033[1;33m 4) Remove Certbot \033[0m                          \033[0;34m|\033[0m"
echo -e "\033[0;34m|\033[0m                                              \033[0;34m|\033[0m"
echo -e "\033[0;34m================================================\033[0m"
echo -e "\033[0;34m|\033[0m    \033[1;36mCertificate generated by Let's Encrypt\033[0m    \033[0;34m|\033[0m"
echo -e "\033[0;34m================================================\033[0m"
echo ""
echo -e "\033[0;36mEnter the desired option: \033[0m"
read x
echo "informed option ($x)"
echo -e "\033[1;36m================================================\033[0m"

case "$x" in

        0)
        echo -e " \033[0;31m Going out  \033[0m"
        clear;
        exit;
        

echo -e "\033[0;34m================================================\033[0m"
;;
        1) #ssl apache install

        apt-get update
        apt-get install software-properties-common -y
        apt-get update
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                 echo -e " \033[0;32mSuccessfully Updated\033[0m"
        fi
        apt-get install certbot -y
        apt install certbot python3-certbot-apache -y
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo -e " \033[0;32mCertbot apache Successfully Installed\033[0m"
        fi
        clear
        certbot --apache
        echo "press enter to continue"
        read z
echo -e "\033[0;34m================================================\033[0m"
;;
        2) # ssl nginx install

        apt-get update
        apt-get install software-properties-common -y
        apt-get update
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo -e " \033[0;32mSuccessfully Updated\033[0m"
        fi
        apt-get install certbot -y
        apt install certbot python3-certbot-nginx -y
        if [ $? -eq 0 ] # check if the command was executed successfully
        then
                echo -e " \033[0;32mCertbot nginx Successfully Installed\033[0m"
        fi
        clear
        certbot --nginx
        echo "press enter to continue"
        read z
echo -e "\033[0;34m================================================\033[0m"
;;
        3)

        certbot renew --dry-run
        echo "press enter to continue"
        read z
echo -e "\033[0;34m================================================\033[0m"
;;
        4)

        echo "removing"
        apt remove certbot python3-certbot-apache -y
        apt-get remove certbot -y
        clear
        echo -e " \033[0;32mCertbot Successfully Removed\033[0m"
        echo "press enter to continue"
        read z
echo -e "\033[0;34m================================================\033[0m"
;;
*)
        echo "Invalid option!"
esac
done
}
menu 